### ISSUE TITLE
Fails to run on Node 8.0

### ISSUE THREAD

**Issue by mahmoudhossam** [engagetech/backend-coding-challenge#10]
I get this error when running `gulp`

```
TypeError: require.extensions.hasOwnProperty is not a function
    at requireDir (/home/mahmoud/Projects/backend-coding-challenge/node_modules/require-dir/index.js:93:37)
    at Object.<anonymous> (/home/mahmoud/Projects/backend-coding-challenge/node_modules/gulp-git/index.js:4:18)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/mahmoud/Projects/backend-coding-challenge/tasks-git.js:10:11)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)

A required module may be missing, try the following command to fix this:
   npm install
```

Versions: 

```
npm --version
4.6.1
node --version
v8.1.2
```

A quick search shows that this is a problem with the npm package [require-dir](https://www.npmjs.com/package/requiredir).

Maybe this project is using an outdated version of this package?

**Comment by pierreh** [comment]
Hi Mahmoud, thank you for letting us know. We are aware of the issue. The project should run fine with Node 4 and Node 6. 
You can try a version manager to install multiple versions of NodeJs.
Like this one: https://github.com/tj/n

**Comment by mahmoudhossam** [comment]
@pierreh I used node 7.0 with nvm as a workaround for now, thanks for your reply.

**Comment by RobeeeJay** [comment]
Fixed in https://github.com/engagetech/backend-coding-challenge/pull/13
